# Generated by Django 5.2.16 on 2026-08-12 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(blank=True, null=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('owner_recruiter_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.UUIDField(blank=True, null=True)),
                ('recruiter_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('work_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('JOB_DESCRIPTION', 'Job Description'), ('EMAIL', 'Email'), ('OFFER', 'Offer')], max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'recruitment_templates',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('position_id', models.UUIDField(blank=True, null=True)),
                ('hiring_manager_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_quantity', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'recruitment_requirements',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer_id', models.UUIDField()),
                ('round', models.CharField(max_length=50)),
                ('status', models.CharField(default='SCHEDULED', max_length=50)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
            ],
            options={
                'db_table': 'recruitment_interviews',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_id', models.UUIDField()),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('offer_details', models.JSONField(default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recruitment.application')),
            ],
            options={
                'db_table': 'recruitment_offers',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer_id', models.UUIDField()),
                ('status', models.CharField(default='SCHEDULED', max_length=50)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='recruitment.application')),
            ],
            options={
                'db_table': 'recruitment_schedules',
            },
        ),
    ]
