// <auto-generated />
using System;
using BBV.HR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BBV.HR.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.BudgetAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adjustment_type");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("BudgetCategory")
                        .HasColumnType("text")
                        .HasColumnName("budget_category");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_budget_adjustments");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_budget_adjustments_approved_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_budget_adjustments_project_id");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_budget_adjustments_requested_by");

                    b.ToTable("budget_adjustments", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_capabilities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_capabilities_name");

                    b.ToTable("capabilities", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employee_code");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.EmployeeCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("capability_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("YearsExperience")
                        .HasColumnType("numeric")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_employee_capabilities");

                    b.HasIndex("CapabilityId")
                        .HasDatabaseName("ix_employee_capabilities_capability_id");

                    b.HasIndex("EmployeeId", "CapabilityId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_capabilities_employee_id_capability_id");

                    b.ToTable("employee_capabilities", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityAppLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("DurationMins")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_productivity_app_logs");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_productivity_app_logs_session_id");

                    b.ToTable("productivity_app_logs", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityScreenshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityPct")
                        .HasColumnType("integer")
                        .HasColumnName("activity_pct");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_productivity_screenshots");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_productivity_screenshots_session_id");

                    b.ToTable("productivity_screenshots", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityPct")
                        .HasColumnType("integer")
                        .HasColumnName("activity_pct");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionType")
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_productivity_sessions");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_productivity_sessions_employee_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_productivity_sessions_project_id");

                    b.ToTable("productivity_sessions", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityWebsiteLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<int?>("DurationMins")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_productivity_website_logs");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_productivity_website_logs_session_id");

                    b.ToTable("productivity_website_logs", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BudgetWarningThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("budget_warning_threshold");

                    b.Property<string>("Client")
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int?>("DefaultWeeklyCapacityH")
                        .HasColumnType("integer")
                        .HasColumnName("default_weekly_capacity_h");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("ExpectedTeamSizeFte")
                        .HasColumnType("integer")
                        .HasColumnName("expected_team_size_fte");

                    b.Property<decimal?>("LaborBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("labor_budget");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TechStack")
                        .HasColumnType("text")
                        .HasColumnName("tech_stack");

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("total_budget");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_projects_created_by");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_projects_manager_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AllocationPct")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_pct");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectRole")
                        .HasColumnType("text")
                        .HasColumnName("project_role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_project_members_employee_id");

                    b.HasIndex("ProjectId", "EmployeeId")
                        .HasDatabaseName("ix_project_members_project_id_employee_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProjectRequiredCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("capability_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("integer")
                        .HasColumnName("required_level");

                    b.Property<int?>("RequiredPeople")
                        .HasColumnType("integer")
                        .HasColumnName("required_people");

                    b.HasKey("Id")
                        .HasName("pk_project_required_capabilities");

                    b.HasIndex("CapabilityId")
                        .HasDatabaseName("ix_project_required_capabilities_capability_id");

                    b.HasIndex("ProjectId", "CapabilityId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_required_capabilities_project_id_capability_id");

                    b.ToTable("project_required_capabilities", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_type");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("timesheet_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id")
                        .HasName("pk_time_entries");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_time_entries_project_id");

                    b.HasIndex("TimesheetId")
                        .HasDatabaseName("ix_time_entries_timesheet_id");

                    b.ToTable("time_entries", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("text")
                        .HasColumnName("reviewer_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.HasKey("Id")
                        .HasName("pk_timesheets");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_timesheets_reviewed_by");

                    b.HasIndex("EmployeeId", "WeekStartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_timesheets_employee_id_week_start_date");

                    b.ToTable("timesheets", (string)null);
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.BudgetAdjustment", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Approver")
                        .WithMany("ApprovedBudgetAdjustments")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_budget_adjustments_employees_approved_by");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Project", "Project")
                        .WithMany("BudgetAdjustments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_adjustments_projects_project_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Requester")
                        .WithMany("RequestedBudgetAdjustments")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_budget_adjustments_employees_requested_by");

                    b.Navigation("Approver");

                    b.Navigation("Project");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.EmployeeCapability", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Capability", "Capability")
                        .WithMany("EmployeeCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_capabilities_capabilities_capability_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Employee")
                        .WithMany("EmployeeCapabilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_capabilities_employees_employee_id");

                    b.Navigation("Capability");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityAppLog", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.ProductivitySession", "Session")
                        .WithMany("AppLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productivity_app_logs_productivity_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityScreenshot", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.ProductivitySession", "Session")
                        .WithMany("Screenshots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productivity_screenshots_productivity_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivitySession", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Employee")
                        .WithMany("ProductivitySessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productivity_sessions_employees_employee_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Project", "Project")
                        .WithMany("ProductivitySessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_productivity_sessions_projects_project_id");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivityWebsiteLog", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.ProductivitySession", "Session")
                        .WithMany("WebsiteLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productivity_website_logs_productivity_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Project", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projects_employees_created_by");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projects_employees_manager_id");

                    b.Navigation("Creator");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProjectMember", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Employee")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_employees_employee_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProjectRequiredCapability", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Capability", "Capability")
                        .WithMany("ProjectRequiredCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_capabilities_capabilities_capability_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Project", "Project")
                        .WithMany("ProjectRequiredCapabilities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_required_capabilities_projects_project_id");

                    b.Navigation("Capability");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.TimeEntry", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_time_entries_projects_project_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Timesheet", "Timesheet")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_entries_timesheets_timesheet_id");

                    b.Navigation("Project");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Timesheet", b =>
                {
                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timesheets_employees_employee_id");

                    b.HasOne("BBV.HR.Infrastructure.Entities.Employee", "Reviewer")
                        .WithMany("ReviewedTimesheets")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_timesheets_employees_reviewed_by");

                    b.Navigation("Employee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Capability", b =>
                {
                    b.Navigation("EmployeeCapabilities");

                    b.Navigation("ProjectRequiredCapabilities");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Employee", b =>
                {
                    b.Navigation("ApprovedBudgetAdjustments");

                    b.Navigation("CreatedProjects");

                    b.Navigation("EmployeeCapabilities");

                    b.Navigation("ManagedProjects");

                    b.Navigation("ProductivitySessions");

                    b.Navigation("ProjectMembers");

                    b.Navigation("RequestedBudgetAdjustments");

                    b.Navigation("ReviewedTimesheets");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.ProductivitySession", b =>
                {
                    b.Navigation("AppLogs");

                    b.Navigation("Screenshots");

                    b.Navigation("WebsiteLogs");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Project", b =>
                {
                    b.Navigation("BudgetAdjustments");

                    b.Navigation("ProductivitySessions");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectRequiredCapabilities");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("BBV.HR.Infrastructure.Entities.Timesheet", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
