
#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/workforce
spring.datasource.username=postgres
spring.datasource.password=phuan03042004

#jpa properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1