spring:
  application:
    name: people
  docker:
    compose:
      enabled: false

server:
  port: 8085

springdoc:
  api-docs:
    path: /api-docs/v1
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
